trigger: none
pr: none

variables:
  appName: 'customgptapp2'
  resourceGroup: 'rggptapp'
  serviceConnection: 'Devops-SP'
  pythonVersion: '3.11'
  zipName: 'fastapi-app.zip'
  unzipPath: 'unzipped-app'

stages:
  - stage: Build
    displayName: 'Build & Zip FastAPI'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        pool:
          vmImage: 'windows-latest'
        steps:
          # Python setup
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
              addToPath: true
            displayName: 'Use Python'

          - script: |
              python -m venv venv
              call venv\Scripts\activate
              pip install -r requirements.txt
            displayName: 'Install Python Dependencies'

          # Zip the entire app
          - powershell: |
              Add-Type -A 'System.IO.Compression.FileSystem'
              [IO.Compression.ZipFile]::CreateFromDirectory("$(Build.SourcesDirectory)", "$(Build.ArtifactStagingDirectory)\$(zipName)")
            displayName: 'Zip FastAPI Project'

          # Publish zipped artifact
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)\$(zipName)'
              ArtifactName: 'fastapi-zipped'
              publishLocation: 'Container'
            displayName: 'Publish Zipped Artifact'

  - stage: Deploy
    displayName: 'Deploy Zipped FastAPI App'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: DeployJob
        displayName: 'Deploy Job'
        pool:
          vmImage: 'windows-latest'
        steps:
          - download: current
            artifact: fastapi-zipped

          - powershell: |
              Expand-Archive -Path "$(Pipeline.Workspace)\fastapi-zipped\$(zipName)" -DestinationPath "$(Pipeline.Workspace)\$(unzipPath)" -Force
            displayName: 'Unzip Artifact to Folder'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(serviceConnection)'
              appType: 'webAppLinux'
              appName: '$(appName)'
              package: '$(Pipeline.Workspace)\$(unzipPath)'
            displayName: 'Deploy Unzipped Folder to Azure'