trigger: none
pr: none

variables:
  appName: 'customgptapp2'
  resourceGroup: 'rggptapp'
  serviceConnection: 'Devops-SP'
  pythonVersion: '3.11'
  packageDir: '$(Build.ArtifactStagingDirectory)'

stages:
  - stage: Build
    displayName: 'Build FastAPI App'
    jobs:
      - job: BuildJob
        displayName: 'Install Dependencies'
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
              addToPath: true
            displayName: 'Use Python $(pythonVersion)'

          - script: |
              python -m venv venv
              call venv\Scripts\activate
              pip install --upgrade pip
              pip install -r requirements.txt
            workingDirectory: '$(Build.SourcesDirectory)'
            displayName: 'Install Python Requirements'

          - script: |
              xcopy /E /I /Y "$(Build.SourcesDirectory)\*" "$(packageDir)\"
            displayName: 'Copy App Files for Deployment'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(packageDir)'
              ArtifactName: 'fastapi-app'
              publishLocation: 'Container'
            displayName: 'Publish FastAPI App Artifact'

  - stage: Deploy
    displayName: 'Deploy to Azure App Service (FastAPI)'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: DeployJob
        displayName: 'Deploy Job'
        pool:
          vmImage: 'windows-latest'
        steps:
          - download: current
            artifact: fastapi-app

          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(serviceConnection)'
              appType: 'webAppLinux'
              appName: '$(appName)'
              package: '$(Pipeline.Workspace)/fastapi-app'
            displayName: 'Deploy FastAPI App to Azure App Service'
